### ISSUE TITLE
panic: runtime error: index out of range [0] with length 0

### ISSUE THREAD

**Issue by hktalent** [projectdiscovery/tlsx#145] opened 2022-12-30 15:06 UTC
cat xx.xml|grep -Eo '((\d{1,3}\.){3,}\d{1,3})'|tlsx -p 443 -nc -o chinaxx.json -json
tlsx  -version
v1.0.0
```
panic: runtime error: index out of range [0] with length 0

goroutine 112 [running]:
github.com/zmap/zcrypto/verifier.CheckOCSP({0x5292658, 0xc000136058}, 0xc003be1000, 0xc000154000?)
	/Users/51pwn/go/pkg/mod/github.com/zmap/zcrypto@v0.0.0-20220803033029-557f3e4940be/verifier/revocation.go:52 +0x57c
github.com/projectdiscovery/tlsx/pkg/tlsx/clients.IsZTLSRevoked(0xc003be1000)
	/Users/51pwn/go/pkg/mod/github.com/projectdiscovery/tlsx@v1.0.0/pkg/tlsx/clients/clients.go:327 +0x35
github.com/projectdiscovery/tlsx/pkg/tlsx/clients.IsTLSRevoked(0xc002137900?)
	/Users/51pwn/go/pkg/mod/github.com/projectdiscovery/tlsx@v1.0.0/pkg/tlsx/clients/clients.go:321 +0x45
github.com/projectdiscovery/tlsx/pkg/tlsx/tls.(*Client).convertCertificateToResponse(0xc000402240, {0xc002137900, 0xd}, 0xc00143c100)
	/Users/51pwn/go/pkg/mod/github.com/projectdiscovery/tlsx@v1.0.0/pkg/tlsx/tls/tls.go:205 +0x1c5
github.com/projectdiscovery/tlsx/pkg/tlsx/tls.(*Client).ConnectWithOptions(0xc000402240, {0xc002137900, 0xd}, {0x0?, 0xc000100000?}, {0xc000136498, 0x3}, {{0x0, 0x0}, {0x0, ...}, ...})
	/Users/51pwn/go/pkg/mod/github.com/projectdiscovery/tlsx@v1.0.0/pkg/tlsx/tls/tls.go:185 +0x8aa
github.com/projectdiscovery/tlsx/pkg/tlsx/auto.(*Client).ConnectWithOptions(0xc000402270, {0xc002137900, 0xd}, {0x0, 0x0}, {0xc000136498, 0x3}, {{0x0, 0x0}, {0x0, ...}, ...})
	/Users/51pwn/go/pkg/mod/github.com/projectdiscovery/tlsx@v1.0.0/pkg/tlsx/auto/auto.go:38 +0xc5
github.com/projectdiscovery/tlsx/pkg/tlsx.(*Service).ConnectWithOptions(0xc000402228, {0xc002137900, 0xd}, {0x0, 0x0}, {0xc000136498, 0x3}, {{0x0, 0x0}, {0x0, ...}, ...})
	/Users/51pwn/go/pkg/mod/github.com/projectdiscovery/tlsx@v1.0.0/pkg/tlsx/tlsx.go:66 +0x116
github.com/projectdiscovery/tlsx/internal/runner.(*Runner).processInputElementWorker(0xc0003c9700, 0x0?, 0x0?)
	/Users/51pwn/go/pkg/mod/github.com/projectdiscovery/tlsx@v1.0.0/internal/runner/runner.go:161 +0x637
created by github.com/projectdiscovery/tlsx/internal/runner.(*Runner).Execute
	/Users/51pwn/go/pkg/mod/github.com/projectdiscovery/tlsx@v1.0.0/internal/runner/runner.go:122 +0x65
```

**Comment by ehsandeep** [comment] 2022-12-31 18:14
Closing as duplicate of https://github.com/projectdiscovery/tlsx/issues/146

**Closed by ehsandeep** 2022-12-31 18:14 UTC
Labels: Type: Bug
