### ISSUE TITLE
SSL Certificate Serial  Support

### ISSUE THREAD

**Issue by pussycat0x** [projectdiscovery/tlsx#202] opened 2023-03-06 12:37 UTC
### Please describe your feature request:

Reference: |
https://www.openssl.org/docs/man1.0.2/man1/openssl-x509.html    
 `-serial`

Shodan Reference: 
![image](https://user-images.githubusercontent.com/65701233/223110339-556bd4e1-b912-4de9-9eb7-88355c710e12.png)

### Describe the use case of this feature:

With a help of SSL Certificate Serial we can identify C2 Server.
Referece: https://michaelkoczwara.medium.com/cobalt-strike-c2-hunting-with-shodan-c448d501a6e2

**Comment by ehsandeep** [comment] 2023-03-07 13:30
@pussycat0x is it duplicate of https://github.com/projectdiscovery/tlsx/issues/190?

**Comment by pussycat0x** [comment] 2023-03-08 04:05
Hi @ehsandeep  yes it's duplicate of #190

**Closed** 2023-03-08 09:13 UTC
Labels: Type: Enhancement
